In [7]:
import torch
import numpy as np

In [26]:
def mean(a):
    return a.mean()

def rms(a):
    return np.sqrt(np.square(a).mean())

def rmc(a):
    return np.cbrt(np.power(a, 3).mean())

def compare(a):
    a = np.array(a)
    print(f'input: {a}')
    print(f'Mean: {mean(a)}')
    print(f'RMS: {rms(a)}')
    print(f'RMC: {rmc(a)}')
    print('')

In [33]:
compare([0.2, 0.3, 0.7])
compare([0.1, 0.2, 0.9])
compare([0.4, 0.5, 0.6])
compare([0.3, 0.3, 0.8])
compare([0.1, 0.8, 0.8])

input: [0.2 0.3 0.7]
Mean: 0.39999999999999997
RMS: 0.4546060565661952
RMC: 0.5013297934964582

input: [0.1 0.2 0.9]
Mean: 0.4000000000000001
RMS: 0.5354126134736337
RMC: 0.6265826556058272

input: [0.4 0.5 0.6]
Mean: 0.5
RMS: 0.5066228051190221
RMC: 0.5129927840030089

input: [0.3 0.3 0.8]
Mean: 0.4666666666666666
RMS: 0.5228129047119374
RMC: 0.573541778662744

input: [0.1 0.8 0.8]
Mean: 0.5666666666666668
RMS: 0.6557438524302002
RMC: 0.6990917926875482



In [9]:
t = torch.tensor([
    [
        [0.2, 0.3, 0.7],
        [0.1, 0.2, 0.9],
    ],
    [
        [0.4, 0.5, 0.6],
        [0.3, 0.3, 0.8],
    ]
])
t

tensor([[[0.2000, 0.3000, 0.7000],
         [0.1000, 0.2000, 0.9000]],

        [[0.4000, 0.5000, 0.6000],
         [0.3000, 0.3000, 0.8000]]])

In [14]:
tsq = torch.mul(t, t)
tsq

tensor([[[0.0400, 0.0900, 0.4900],
         [0.0100, 0.0400, 0.8100]],

        [[0.1600, 0.2500, 0.3600],
         [0.0900, 0.0900, 0.6400]]])

In [16]:
tm = tsq.mean(dim=0, keepdims=True)
tm

tensor([[[0.1000, 0.1700, 0.4250],
         [0.0500, 0.0650, 0.7250]]])

In [19]:
torch.sqrt(tm)

tensor([[[0.3162, 0.4123, 0.6519],
         [0.2236, 0.2550, 0.8515]]])

In [28]:
np.cbrt(0.3)

0.6694329500821694

In [32]:
t = torch.tensor(0.3)
p = torch.tensor(1/3)
torch.pow(t, p)

tensor(0.6694)