In [1]:
import numpy as np

In [2]:
a = np.array([1, 0, 1, 0])
a

array([1, 0, 1, 0])

In [3]:
e = 1e-8
n = 1/10
m = 10 * (1 - e)
print(e, n, m)

1e-08 0.1 9.999999899999999


In [4]:
a_ = (a * m + e) * n
a_

array([9.99999991e-01, 1.00000000e-09, 9.99999991e-01, 1.00000000e-09])

In [5]:
e = 1e-8
n = (1 - 2 * e)
b = (e) / (1 - 2 * e)

In [6]:
a_ = (a + b) * n
a_

array([9.9999999e-01, 1.0000000e-08, 9.9999999e-01, 1.0000000e-08])